export const modalidades = [
  'BALLET CLÁSICO',
  'BALLET NEO - CLÁSICO',
  'DANZA MODERNA Y CONTEMPORANEA',
  'JAZZ',
  'MUSICAL',
  'TAP DANCE',
  'STREET DANCE',
  'BAILES TROPICALES Y DE SALÓN',
  'FOLKLORE ETNICO Y DE RAIZ',
  'FOLKLORE NACIONAL E INTERNACIONAL',
  'FOLKLORE NACIONAL E INTERNACIONAL DEPROYECCIÓN',
  'DANZAS POPULARES',
  'K-POP',
  'RETRO - DANCE'
]
