export const modalidades = [
  'BALLET CLASICO',
  'BALLET NEO - CLASICO',
  'DANZA MODERNA Y CONTEMPORANEA',
  'JAZZ',
  'MUSICAL',
  'TAP DANCE',
  'STREET DANCE',
  'BAILES TROPICALES Y DE SALON',
  'FOLKLORE ETNICO Y DE RAIZ',
  'FOLKLORE NACIONAL E INTERNACIONAL',
  'FOLKLORE NACIONAL E INTERNACIONAL DEPROYECCION',
  'DANZAS POPULARES',
  'K-POP',
  'RETRO - DANCE'
]
